#!/usr/bin/ansible-playbook
# Author: apined12@its.jnj.com
---
- name: F5 Onboarding
  hosts: bigip 
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "setup_password"
      prompt: "Enter admin password"
      private: yes

  roles:
    - jnjf5onboarding
